name: Run API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install fastapi uvicorn pytest httpx

      - name: Verify test file exists
        run: ls -R   # This prints the directory structure for debugging

      - name: Run Tests
        run: pytest tests/   # ✅ Updated to run all tests in the `tests/` folder
